# permissions for end users to view cronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-book
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-viewer-role
rules:
- apiGroups:
  - batch.psrvere.in
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.psrvere.in
  resources:
  - cronjobs/status
  verbs:
  - get
