apiVersion: batch.psrvere.in/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-book
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  # TODO(user): Add fields here
